#!/usr/bin/env bash

## PHASE 2: BUILD THE IMAGE - this script makes a Docker container for the 
## purpose of creating the image that we have already built the kernel for. 
## Like the other container, this container exists to isolate the performance 
## of a script,src/make-image.


docker run --privileged --rm -v /dev:/dev:ro -v "$PWD/src":/src -v "$PWD/img":/img -w /src \
    -e ALPINE_MIRROR="http://dl-cdn.alpinelinux.org/alpine" \
    -e ALPINE_VERSION=3.10.3 \
    -e ARCH=aarch64 \
    -e KERNEL_REPO="https://github.com/raspberrypi/firmware" \
    -e KERNEL_BUILD_DIR=/img/rpi-kernel \
    -e ROOT_PASSWORD=${ROOT_PASSWORD} \
    -e CACHE_DIR=/img/cache \
    alpine ./make-image

#    -e KERNEL_BUILD_DIR=/img/rpi-kernel \
#    -e KERNEL_VERSION=4.19.88-v8+ \
