#!/usr/bin/env bash

# Step 1: Build the RPI kernel. This is accomplished with this docker command.Pretty nifty stuff, doing it this way  prevents any issues arising that would kill your workstation by providing a 
# a layer of abstraction between your machine and the kernel configuration that also happens to be... in a reproducible environment. LINUX IS PRETTY SLICK

docker run --privileged --rm -v /dev:/dev:ro -v "$PWD/src":/src -v "$PWD/img":/img -w /src \
    -e RPI_REPO="https://github.com/raspberrypi/linux.git" \
    -e RPI_BRANCH=rpi-4.19.y \
    -e ARCH=arm64 \
    -e TARGET_ARCH=aarch64 \
    -e TOOLCHAIN_DIR=/img/toolchains \
    -e SOURCE_DIR=/img/rpi-linux \
    -e KERNEL_BUILD_DIR=/img/rpi-kernel \
    alpine ./make-kernel
